//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitstampTransactionHistoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicTransaction
    {
        public int tid { get; set; }
        public byte[] date { get; set; }
        public decimal price { get; set; }
        public decimal amount { get; set; }
        public bool type { get; set; }
    }
}
